### ISSUE TITLE
Our build and deployment script/process needs evaluated

### ISSUE THREAD

**Issue by CGibney** [CGibney/by-om#6]
We may need a different tool, script, or process to automate the cloning, building, and deployment of this project on Raspbian

**Comment by SpaceLawd** [comment]
Will this work. It makes Git less intimidating for new users and might help speed the process along:

https://www.gitkraken.com/glo

**Comment by CGibney** [comment]
Great suggestion. I encourage you to discuss this in our Daily Scrum/Sprint
Planning threads, as I've noticed how hard it's been for us to use git.
There's also the GitHub app, but I'm not sure if that works on *nix OSes.

Thanks

**Comment by CGibney** [comment]
Going forward with Docker, to deprecate the shell script. Runs pretty quick once it's all cached from the first time you build the image!
